import 'package:flutter/material.dart';

class LangHelper {
  static final Map<String, Map<String, String>> _localizedValues = {
    // دری (فارسی افغانستان)
    'fa': {
      'home': 'اصلی صفحه',
      'profile': 'پروفایل ادمین',
      'settings': 'تنظیمات سیستم',
      'support': 'تشتیبانی فنی',
      'exit': 'خروج از حساب',
      'reg_title': 'ثبت‌نام سفیر جدید',
      'manage_drivers': 'مدیریت رانندگان سفیر',
      'driver_name': 'نام راننده',
      'car_details': 'مشخصات خودرو',
      'phone_number': 'شماره تماس',
      'total_earnings': 'کل درآمد',
      'account_status': 'وضعیت حساب',
      'more_details': 'جزئیات بیشتر',
      'active_drivers': 'رانندگان فعال',
      'blocked_drivers': 'رانندگان مسدود شده',
      'manage_users': 'مدیریت مسافران سفیر',
      'user_name': 'نام مسافر',
      'email': 'ایمیل',
      'total_trips': 'تعداد سفرها',
      'active_rides': 'سفرهای فعال',
      'trip_id': 'آیدی سفر',
      'origin': 'مبدأ',
      'destination': 'مقصد',
      'fare': 'کرایه (افغانی)',
      'date': 'تاریخ و زمان',
      'total_earned': 'مجموع درآمد',
      'send_notification': 'ارسال اعلان جدید',
      'notif_title': 'عنوان اعلان',
      'notif_body': 'متن اعلان',
      'submit': 'تایید و ارسال',
      'cancel': 'انصراف',
    },
    // پشتو
    'ps': {
      'home': 'اصلي صفحه',
      'profile': 'د ادمین پروفایل',
      'settings': 'د سیسټم تنظیمات',
      'support': 'تخنیکي ملاتړ',
      'exit': 'له حساب څخه وتل',
      'reg_title': 'د نوي سفیر نوم لیکنه',
      'manage_drivers': 'د سفیر چلوونکو مدیریت',
      'driver_name': 'د چلوونکي نوم',
      'car_details': 'د موټر مشخصات',
      'phone_number': 'د اړيکې شمېره',
      'total_earnings': 'ټوله اټکل شوې ګټه',
      'account_status': 'د حساب حالت',
      'more_details': 'نور جزئیات',
      'active_drivers': 'فعال چلوونکي',
      'blocked_drivers': 'بند شوي چلوونکي',
      'manage_users': 'د سفیر د مسافرو مدیریت',
      'user_name': 'د مسافر نوم',
      'email': 'بریښنالیک',
      'total_trips': 'د سفرونو شمیر',
      'active_rides': 'فعال سفرونه',
      'trip_id': 'د سفر آیدي',
      'origin': 'مبدأ',
      'destination': 'مقصد',
      'fare': 'کرایه (افغانۍ)',
      'date': 'نیټه او وخت',
      'total_earned': 'ټوله ګټه',
      'send_notification': 'د نوي خبرتیا لیږل',
      'notif_title': 'د خبرتیا سرلیک',
      'notif_body': 'د خبرتیا متن',
      'submit': 'تایید او لیږل',
      'cancel': 'بندول',
    },
    // انگلیسی
    'en': {
      'home': 'Dashboard',
      'profile': 'Admin Profile',
      'settings': 'System Settings',
      'support': 'Technical Support',
      'exit': 'Logout',
      'reg_title': 'Register New Safir',
      'manage_drivers': 'Safir Drivers Management',
      'driver_name': 'Driver Name',
      'car_details': 'Car Details',
      'phone_number': 'Phone Number',
      'total_earnings': 'Total Earnings',
      'account_status': 'Account Status',
      'more_details': 'More Details',
      'active_drivers': 'Active Drivers',
      'blocked_drivers': 'Blocked Drivers',
      'manage_users': 'Safir Passengers Management',
      'user_name': 'Passenger Name',
      'email': 'Email',
      'total_trips': 'Total Trips',
      'active_rides': 'Active Trips',
      'trip_id': 'Trip ID',
      'origin': 'Origin',
      'destination': 'Destination',
      'fare': 'Fare (AFN)',
      'date': 'Date & Time',
      'total_earned': 'Total Earned',
      'send_notification': 'Send New Notification',
      'notif_title': 'Notification Title',
      'notif_body': 'Notification Message',
      'submit': 'Submit & Send',
      'cancel': 'Cancel',
    },
  };

  static String getString(BuildContext context, String key) {
    String langCode = Localizations.localeOf(context).languageCode;
    return _localizedValues[langCode]?[key] ?? key;
  }
}

String tr(BuildContext context, String key) {
  return LangHelper.getString(context, key);
}
